### PR TITLE
linux-arm64 build

### PR DESCRIPTION
**Pull request by a-ronjohnson**

### CODE REVIEW

**Comment by a-ronjohnson** [comment]
Was able to create build with prebuild-linux-arm64 script, and test it on AWS Graviton2 (arm64) Ubuntu instance.

**Comment by a-ronjohnson** [comment]
Hello! - As a new contributor I can't run the test workflow, but let me know if I can otherwise help with this.

**Comment by wadey** [comment]
I think this looks good! I'll take a closer look tomorrow and try to do a test release to confirm. Thanks!

**Comment by wadey** [comment]
Test release looks good, ill merge and do release when I have moment. Thanks again!

- https://github.com/wadey/node-microtime/releases/tag/v3.1.0-test-linux-arm64-build

**Comment by wadey** [comment]
Thanks for the PR, this was released as 3.1.1

**Comment by a-ronjohnson** [comment]
Awesome! Thanks!

**Pull request merged**
