### PR TITLE
expose the bound module directly

### PR DESCRIPTION
**Pull request by thefourtheye**

### CODE REVIEW

**Comment by wadey** [comment]
Is there a reason this is needed besides code cleanup?

**Comment by thefourtheye** [comment]
@wadey Nope, just code cleanup. When I noticed this code, I went to the `microtime.cc` to see if it exposes any other functions and it actually doesn't. So I realised this is just superfluous.

**Comment by wadey** [comment]
I like having the methods listed out because it makes it easier for someone to take a quick glance at the JS code and see what methods are available in this module without having to open up the C++ code and understand it. So I'm going to leave it the way it is.

**Comment by thefourtheye** [comment]
No problem. Thanks for taking a look at it :-)

**Pull request closed without merging**
