### PR TITLE
Node.js and io.js native addon build tool

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by Globegitter** [comment]
:+1:

**Comment by wadey** [comment]
Can you explain why this was needed? I tested the current version of microtime with both Node.js and iojs and it worked for both (back when I released it). I'm away from my computer until late next week but I'll check again when I can.

**Comment by listepo** [comment]
@wadey node-gyp does not work on the iojs latest see https://travis-ci.org/balderdashy/sails/jobs/55336712

**Comment by wadey** [comment]
It looks like all that is needed is an update to the `nan` module, no need to switch to pangyp and remove 0.8 compatibility: https://travis-ci.org/wadey/node-microtime/builds/57148550

I released microtime 1.3.0 with this change, can you test it out?

**Comment by listepo** [comment]
```
gyp ERR! cwd /Users/ivan/Github/node-microtime
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/ivan/.nvm/versions/io.js/v1.6.2/bin/iojs" "/Users/ivan/.nvm/versions/io.js/v1.6.2/bin/npm" "install"
npm ERR! node v1.6.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! microtime@1.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the microtime@1.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the microtime package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls microtime
npm ERR! There is likely additional logging output above.
```

**Comment by listepo** [comment]
Work only iojs-v1.6.3

**Comment by wadey** [comment]
Yes looks like this fix landed in 1.6.3 that fixes node-gyp: https://github.com/iojs/io.js/pull/990

**Comment by listepo** [comment]
I think the problem is solved, thanks

**Pull request closed without merging**
